branding:
  color: orange
  icon: triangle
description: 'Receive the deployment preview URL from Cloudflare'
inputs:
  cloudflare_project_id:
    description: 'Cloudflare project id / name'
    required: true
  wait_until_ready:
    description: 'Wait for deployment to be ready'
    required: false
    default: ''
  environment:
    description:
      "Which Cloudflare deployment environments to allow. If set to null,
      doesn't filter deploys by environment. Defaults to 'preview'"
    required: false
    default: 'preview'
  commit_hash:
    description:
      'Optional commit hash to filter deployments on. Useful when the same
      branch can have multiple deploys.'
    required: false
  branch:
    description:
      'Optional branch name to filter deployments on. Useful when the branch
      name is not available in the action context.'
    required: false
name: Cloudflare Preview URL
outputs:
  preview_url:
    description:
      'A string with the unique URL of the deployment. Always set when a
      deployment is found, regardless of deployment status.'
runs:
  main: dist/index.js
  using: node24
